### PR TITLE
Some edits to PR #771

### PR DESCRIPTION
**Pull request by johnyangk**
@seojangho - as we've discussed offline, I’ve made some changes to your branch to understand the overall scheduler code myself and make synchronization points more explicit. Please take a look, and let me know if it looks good to be merged into your branch.

Note that I was not able to run tests, due to the bugs currently present in the master branch.

Code summary
- Only two threads call scheduling code: RuntimeMaster thread (RMT), and SchedulerThread(ST)
- RMT and ST meet only at two points: SchedulingPolicy, and PendingTaskGroupQueue, which are synchronized(ThreadSafe)
- Other scheduler-related classes that are accessed by only one of the two threads are not synchronized(NotThreadSafe)
- We use ContainerManager for handling containers only, and not executors (to avoid hanging, we also don’t wait for pending resource requests upon termination)
- ExecutorRegistry and ExecutorRepresenter fully classify running/failed/completed Executor/Taskgroups

### CODE REVIEW

**Comment by seojangho** [comment]
Thanks for the changes. I'll merge #798 and do tests.

**Comment by bgchun** [comment]
This PR should be moved to incubator-nemo.

**Review by seojangho — COMMENTED** [review]
Thanks for the work. Overall, LGTM.

**Comment by johnyangk** [comment]
@bgchun Will move to incubator-nemo.

**Pull request closed without merging**
