### PR TITLE
[Onyx-692] Support Java9

### LINKED ISSUE #692: Support Java 9
Java 9 came out last September, and it seems worth considering supporting Java 9.
According to an article, it claims the following attributes:

- Better Use of Memory
- Better Performance
- Better Use of Hardware
- Better Documentation
- Prettier Graphics
- Faster Compilation

[Maven 3.0+ seem to work well with Java 9](https://twitter.com/rfscholte/status/864560567767498752), and we can use REPL via JShell and interfaces with more features, as well as immutable maps and lists.

### PR DESCRIPTION
**Pull request by wonook**
This PR:

- upgrades old dependency and plugin versions to support Java 9
  - Mockito 1 to 2 with appropriate changes

I've tested on my mac with Java 9.0.1. It works well with the following changes.

resolves #692.

### CODE REVIEW

**Comment by wonook** [comment]
Jenkins (Java 8) seems like it's working as well! 😄 
Could anyone check and merge?

**Comment by bgchun** [comment]
Onyx's not used in a stand alone in production pipelines. If Onyx gets ever used in production environments, it should co-work with other software running in companies. It's not likely that it's Java-9 ready. Let's not rush into Java9.

**Comment by wonook** [comment]
Sure! I will leave Jenkins to use Java 8 to check the compatibility. This PR simply upgrades packages to make our project compatible with Java 9 in addition to Java 8.

**Comment by sanha** [comment]
I've tested this branch with yarn cluster environment (Java 8) and it worked well. I'll merge this.

**Pull request merged**
